# .github/workflows/scheduled-builds.yml
name: Check the Bevy repository for updates

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: "55 * * * *"
  workflow_dispatch:
jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for Bevy updates
        run: |
          git clone --bare https://github.com/bevyengine/bevy tmpdir
          cd tmpdir
          if ! git rev-parse HEAD | grep -q `cat ../latest-commit`; then
            git rev-parse HEAD > ../latest-commit

            cd ..
            git config --local user.email "$(git log --format='%ae' HEAD^!)"
            git config --local user.name "$(git log --format='%an' HEAD^!)"
            git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
            git pull github meta --ff-only
            git commit -m "Set latest commit" latest-commit
            git push github HEAD:meta

            true
          else
            false
          fi
      - if: ${{ success() }}
        name: Invoke Example Runner
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Run Examples
          token: ${{ secrets.PERSONAL_TOKEN }}
