name: Run Examples

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: Force

env:
  LIBGL_ALWAYS_SOFTWARE: true
  GALLIUM_DRIVER: llvmpipe

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.compare-commit.outputs.updated }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "workflow-status"
          path: "workflow-status"
      - uses: actions/checkout@v3
        with:
          repository: "bevyengine/bevy"
          path: "bevy"
          fetch-depth: 0
      - name: Check for Bevy updates
        id: compare-commit
        run: |
          cd bevy
          if ! git rev-parse HEAD | grep -q `cat ../workflow-status/latest-commit`; then
            git rev-parse HEAD > ../workflow-status/latest-commit
            cd ../workflow-status

            git config user.name 'Workflow'
            git config user.email '<>'

            git add latest-commit
            git commit --amend -m "Update Latest Commit"
            git push --force

            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "No updates"
            echo "updated=false" >> $GITHUB_OUTPUT
          fi
  run-examples:
    needs: check
    if: ${{ needs.check.outputs.updated == 'true' || github.event.inputs.force == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: "results"
          path: "results"
      - uses: actions/checkout@v3
        with:
          repository: "bevyengine/bevy"
          path: "bevy"
      - name: Download rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            bevy/target/debug/build
            bevy/target/debug/deps
            bevy/target/debug/incremental
          key: ${{ runner.os }}-cargo-build-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.toml') }}
      - name: Install Bevy dependencies
        run: |
          sudo apt-get update;
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -yq \
            libasound2-dev libudev-dev;
      - name: Install xvfb, llvmpipe and lavapipe
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:oibaf/graphics-drivers -y
          sudo apt-get update
          sudo apt install -y xvfb libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
      - name: Build bevy
        run: |
          cd bevy

          echo "" >> Cargo.toml
          echo "[profile.dev]" >> Cargo.toml
          echo "opt-level = 1" >> Cargo.toml
          echo "[profile.dev.package.\"*\"]" >> Cargo.toml
          echo "opt-level = 3" >> Cargo.toml

          cargo build --features="x11,bevy_ci_testing"
      - name: Run examples
        run: |
          cargo run --bin run_examples -- --xvfb
      - name: Archive xvfb log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: xvfb-log
          path: bevy/xvfb.log
      - name: Store results
        run: |
          cd results

          git config user.name 'Workflow'
          git config user.email '<>'

          git add .
          git commit -m "Update Results"
          git push
  build-website:
    needs: run-examples
    if: ${{ needs.check.outputs.updated == 'true' || github.event.inputs.force == 'true' }}
    uses: ./.github/workflows/build_website.yml
